[tool.poetry]
name = "torch_flatbuffers"
version = "0.1.0"
description = ""
authors = ["Dawid Kobus <machineko@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.1"
torch = "^1.12.0"
flatbuffers = "^2.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
