# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Layer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Layer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLayer(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Layer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Layer
    def Idx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Layer
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Layer
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Layer
    def Weights(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def WeightsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Layer
    def WeightsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def WeightsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Layer
    def WeightsShape(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def WeightsShapeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Layer
    def WeightsShapeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def WeightsShapeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Layer
    def Bias(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def BiasAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Layer
    def BiasLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def BiasIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Layer
    def BiasShape(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def BiasShapeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Layer
    def BiasShapeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def BiasShapeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # Layer
    def Probability(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Layer
    def StartDim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Layer
    def EndDim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Layer
    def OutSize(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def OutSizeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Layer
    def OutSizeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def OutSizeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # Layer
    def Eps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Layer
    def Momentum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Layer
    def NumBatchesTracked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Layer
    def RunningMean(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def RunningMeanAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Layer
    def RunningMeanLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def RunningMeanIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # Layer
    def RunningMeanShape(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def RunningMeanShapeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Layer
    def RunningMeanShapeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def RunningMeanShapeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        return o == 0

    # Layer
    def RunningVar(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def RunningVarAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Layer
    def RunningVarLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def RunningVarIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        return o == 0

    # Layer
    def RunningVarShape(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def RunningVarShapeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Layer
    def RunningVarShapeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def RunningVarShapeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        return o == 0

    # Layer
    def KernelSize(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def KernelSizeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Layer
    def KernelSizeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def KernelSizeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        return o == 0

    # Layer
    def Dilation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def DilationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Layer
    def DilationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def DilationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        return o == 0

    # Layer
    def Groups(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Layer
    def InChannels(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Layer
    def OutChannels(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Layer
    def PadMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Layer
    def Padding(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def PaddingAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Layer
    def PaddingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def PaddingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        return o == 0

    # Layer
    def Stride(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Layer
    def StrideAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Layer
    def StrideLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Layer
    def StrideIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        return o == 0

    # Layer
    def DataLayout(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Layer
    def CeilMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Start(builder): builder.StartObject(28)
def LayerStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddIdx(builder, idx): builder.PrependInt32Slot(0, idx, 0)
def LayerAddIdx(builder, idx):
    """This method is deprecated. Please switch to AddIdx."""
    return AddIdx(builder, idx)
def AddType(builder, type): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)
def LayerAddType(builder, type):
    """This method is deprecated. Please switch to AddType."""
    return AddType(builder, type)
def AddName(builder, name): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def LayerAddName(builder, name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, name)
def AddWeights(builder, weights): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(weights), 0)
def LayerAddWeights(builder, weights):
    """This method is deprecated. Please switch to AddWeights."""
    return AddWeights(builder, weights)
def StartWeightsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartWeightsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartWeightsVector(builder, numElems)
def AddWeightsShape(builder, weightsShape): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(weightsShape), 0)
def LayerAddWeightsShape(builder, weightsShape):
    """This method is deprecated. Please switch to AddWeightsShape."""
    return AddWeightsShape(builder, weightsShape)
def StartWeightsShapeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartWeightsShapeVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartWeightsShapeVector(builder, numElems)
def AddBias(builder, bias): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(bias), 0)
def LayerAddBias(builder, bias):
    """This method is deprecated. Please switch to AddBias."""
    return AddBias(builder, bias)
def StartBiasVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartBiasVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartBiasVector(builder, numElems)
def AddBiasShape(builder, biasShape): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(biasShape), 0)
def LayerAddBiasShape(builder, biasShape):
    """This method is deprecated. Please switch to AddBiasShape."""
    return AddBiasShape(builder, biasShape)
def StartBiasShapeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartBiasShapeVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartBiasShapeVector(builder, numElems)
def AddProbability(builder, probability): builder.PrependFloat32Slot(7, probability, 0.0)
def LayerAddProbability(builder, probability):
    """This method is deprecated. Please switch to AddProbability."""
    return AddProbability(builder, probability)
def AddStartDim(builder, startDim): builder.PrependInt32Slot(8, startDim, 0)
def LayerAddStartDim(builder, startDim):
    """This method is deprecated. Please switch to AddStartDim."""
    return AddStartDim(builder, startDim)
def AddEndDim(builder, endDim): builder.PrependInt32Slot(9, endDim, 0)
def LayerAddEndDim(builder, endDim):
    """This method is deprecated. Please switch to AddEndDim."""
    return AddEndDim(builder, endDim)
def AddOutSize(builder, outSize): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(outSize), 0)
def LayerAddOutSize(builder, outSize):
    """This method is deprecated. Please switch to AddOutSize."""
    return AddOutSize(builder, outSize)
def StartOutSizeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartOutSizeVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartOutSizeVector(builder, numElems)
def AddEps(builder, eps): builder.PrependFloat32Slot(11, eps, 0.0)
def LayerAddEps(builder, eps):
    """This method is deprecated. Please switch to AddEps."""
    return AddEps(builder, eps)
def AddMomentum(builder, momentum): builder.PrependFloat32Slot(12, momentum, 0.0)
def LayerAddMomentum(builder, momentum):
    """This method is deprecated. Please switch to AddMomentum."""
    return AddMomentum(builder, momentum)
def AddNumBatchesTracked(builder, numBatchesTracked): builder.PrependInt32Slot(13, numBatchesTracked, 0)
def LayerAddNumBatchesTracked(builder, numBatchesTracked):
    """This method is deprecated. Please switch to AddNumBatchesTracked."""
    return AddNumBatchesTracked(builder, numBatchesTracked)
def AddRunningMean(builder, runningMean): builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(runningMean), 0)
def LayerAddRunningMean(builder, runningMean):
    """This method is deprecated. Please switch to AddRunningMean."""
    return AddRunningMean(builder, runningMean)
def StartRunningMeanVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartRunningMeanVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartRunningMeanVector(builder, numElems)
def AddRunningMeanShape(builder, runningMeanShape): builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(runningMeanShape), 0)
def LayerAddRunningMeanShape(builder, runningMeanShape):
    """This method is deprecated. Please switch to AddRunningMeanShape."""
    return AddRunningMeanShape(builder, runningMeanShape)
def StartRunningMeanShapeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartRunningMeanShapeVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartRunningMeanShapeVector(builder, numElems)
def AddRunningVar(builder, runningVar): builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(runningVar), 0)
def LayerAddRunningVar(builder, runningVar):
    """This method is deprecated. Please switch to AddRunningVar."""
    return AddRunningVar(builder, runningVar)
def StartRunningVarVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartRunningVarVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartRunningVarVector(builder, numElems)
def AddRunningVarShape(builder, runningVarShape): builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(runningVarShape), 0)
def LayerAddRunningVarShape(builder, runningVarShape):
    """This method is deprecated. Please switch to AddRunningVarShape."""
    return AddRunningVarShape(builder, runningVarShape)
def StartRunningVarShapeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartRunningVarShapeVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartRunningVarShapeVector(builder, numElems)
def AddKernelSize(builder, kernelSize): builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(kernelSize), 0)
def LayerAddKernelSize(builder, kernelSize):
    """This method is deprecated. Please switch to AddKernelSize."""
    return AddKernelSize(builder, kernelSize)
def StartKernelSizeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartKernelSizeVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartKernelSizeVector(builder, numElems)
def AddDilation(builder, dilation): builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(dilation), 0)
def LayerAddDilation(builder, dilation):
    """This method is deprecated. Please switch to AddDilation."""
    return AddDilation(builder, dilation)
def StartDilationVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartDilationVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartDilationVector(builder, numElems)
def AddGroups(builder, groups): builder.PrependInt32Slot(20, groups, 0)
def LayerAddGroups(builder, groups):
    """This method is deprecated. Please switch to AddGroups."""
    return AddGroups(builder, groups)
def AddInChannels(builder, inChannels): builder.PrependInt32Slot(21, inChannels, 0)
def LayerAddInChannels(builder, inChannels):
    """This method is deprecated. Please switch to AddInChannels."""
    return AddInChannels(builder, inChannels)
def AddOutChannels(builder, outChannels): builder.PrependInt32Slot(22, outChannels, 0)
def LayerAddOutChannels(builder, outChannels):
    """This method is deprecated. Please switch to AddOutChannels."""
    return AddOutChannels(builder, outChannels)
def AddPadMode(builder, padMode): builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(padMode), 0)
def LayerAddPadMode(builder, padMode):
    """This method is deprecated. Please switch to AddPadMode."""
    return AddPadMode(builder, padMode)
def AddPadding(builder, padding): builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(padding), 0)
def LayerAddPadding(builder, padding):
    """This method is deprecated. Please switch to AddPadding."""
    return AddPadding(builder, padding)
def StartPaddingVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartPaddingVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartPaddingVector(builder, numElems)
def AddStride(builder, stride): builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(stride), 0)
def LayerAddStride(builder, stride):
    """This method is deprecated. Please switch to AddStride."""
    return AddStride(builder, stride)
def StartStrideVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LayerStartStrideVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartStrideVector(builder, numElems)
def AddDataLayout(builder, dataLayout): builder.PrependUOffsetTRelativeSlot(26, flatbuffers.number_types.UOffsetTFlags.py_type(dataLayout), 0)
def LayerAddDataLayout(builder, dataLayout):
    """This method is deprecated. Please switch to AddDataLayout."""
    return AddDataLayout(builder, dataLayout)
def AddCeilMode(builder, ceilMode): builder.PrependBoolSlot(27, ceilMode, 0)
def LayerAddCeilMode(builder, ceilMode):
    """This method is deprecated. Please switch to AddCeilMode."""
    return AddCeilMode(builder, ceilMode)
def End(builder): return builder.EndObject()
def LayerEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)